<?php
/**
* NOTICE OF LICENSE
*
* Copyright (c) 2012 Litle & Co.
*
* Permission is hereby granted, free of charge, to any person
* obtaining a copy of this software and associated documentation
* files (the "Software"), to deal in the Software without
* restriction, including without limitation the rights to use,
* copy, modify, merge, publish, distribute, sublicense, and/or sell
* copies of the Software, and to permit persons to whom the
* Software is furnished to do so, subject to the following
* conditions:
*
* The above copyright notice and this permission notice shall be
* included in all copies or substantial portions of the Software.
*
* THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
* EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES
* OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
* NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
* HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
* WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
* FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
* OTHER DEALINGS IN THE SOFTWARE.
*
* @category   Litle
* @copyright  Copyright (c) 2012 Litle & Co.
* @license    http://www.opensource.org/licenses/mit-license.php
* @author     Litle & Co <sdksupport@litle.com> www.litle.com/developers
*/
?>
<?php

//$customerId = Mage::getSingleton('adminhtml/session_quote')->getCustomer()->getData("entity_id");
$purchases = Mage::helper('creditcard')->uniqueCreditCard(Mage::getSingleton('adminhtml/session_quote')->getCustomer()->getData("entity_id"));
$_paypageEnabled = Mage::getModel('Litle_CreditCard_Model_PaymentLogic')->getConfigData("paypage_enable");
$_code=$this->getMethodCode();
?>

	<?php if($_paypageEnabled == 1):?>
   		<ul id="payment_form_<?php echo $_code ?>" style="display:none;">
			<a href="https://vt.litle.com" target="_blank">Litle Virtual Terminal</a>
<br>
<br>
	<?php if ($purchases[0]['last4'] !== NULL): ?>
	<li>
        <label for="<?php echo $_code ?>_cc_vaulted" class=""><?php echo $this->__('Stored Credit Cards') ?></label>
        <div class="input-box">
            <select id="<?php echo $_code ?>_cc_vaulted" name="payment[cc_vaulted]">
                <option value><?php echo $this->__('--Please Select A Stored Credit Card--')?></option>
	    <?php $i = 1; ?>
            <?php foreach ($purchases as $key => $value): ?>
                <option value ="<?php echo ($i)?>"><?php echo 'Stored ' . $purchases[$i-1]['type'] . ' Ending in: ' . $purchases[$i-1]['last4'] ?></option>
	    <?php $i++ ?>
            <?php endforeach ?>
            </select>
        </div>
    </li>
    <li id="<?php echo $_code ?>_cc_type_cvv_div">
        <label id = "creditcard_cc_cid_label" for="<?php echo $_code ?>_cc_cid" class=""><?php echo $this->__('Card Verification Number') ?></label>
        <div class="input-box">
            <div class="v-fix">
                <input type="text" title="<?php echo $this->__('Card Verification Number') ?>" class="input-text " id="<?php echo $_code ?>_cc_cid" name="payment[cc_cid]" value="" />
            </div>
        </div>
    </li>
		</ul>
		<script type="text/javascript">
		$('creditcard_cc_cid').hide();
		$('creditcard_cc_cid_label').hide();

		var selectmenu=document.getElementById("<?php echo $_code ?>_cc_vaulted");
		selectmenu.onchange=function(){
			var chosenoption=this.options[this.selectedIndex]
			if (chosenoption.value!= 0){
				$('creditcard_cc_cid').show();
				$('creditcard_cc_cid_label').show();
				$('creditcard_cc_cid').value="";
				
			}
			if (chosenoption.value == 0){
				$('creditcard_cc_cid').hide();
				$('creditcard_cc_cid_label').hide();
			}
		}
		</script>

	<?php endif; ?><?php endif; ?>
	<?php if($_paypageEnabled != 1):?>
   		<ul class="form-list" id="payment_form_<?php echo $_code ?>" style="display:none;">
		    <li>
		        <label for="<?php echo $_code ?>_cc_type" class="required"><em>*</em><?php echo $this->__('Credit Card Type') ?></label>
		        <div class="input-box">
		            <select id="<?php echo $_code ?>_cc_type" name="payment[cc_type]" class="required-entry validate-cc-type-select">
		                <option value=""><?php echo $this->__('--Please Select--')?></option>
		            <?php $_ccType = $this->getInfoData('cc_type') ?>
		            <?php foreach ($this->getCcAvailableTypes() as $_typeCode => $_typeName): ?>
		                <option value="<?php echo $_typeCode ?>"<?php if($_typeCode==$_ccType): ?> selected="selected"<?php endif ?>><?php echo $_typeName ?></option>
		            <?php endforeach ?>
		            </select>
		        </div>
		    </li>
		    <li>
		        <label for="<?php echo $_code ?>_cc_number" class="required"><em>*</em><?php echo $this->__('Credit Card Number') ?></label>
		        <div class="input-box">
		            <input type="text" id="<?php echo $_code ?>_cc_number" name="payment[cc_number]" title="<?php echo $this->__('Credit Card Number') ?>" class="input-text validate-cc-number validate-cc-type" value="" />
		        </div>
		    </li>
		    <li id="<?php echo $_code ?>_cc_type_exp_div">
		        <label for="<?php echo $_code ?>_expiration" class="required"><em>*</em><?php echo $this->__('Expiration Date') ?></label>
		        <div class="input-box">
		            <div class="v-fix">
		                <select id="<?php echo $_code ?>_expiration" name="payment[cc_exp_month]" class="month validate-cc-exp required-entry">
		                <?php $_ccExpMonth = $this->getInfoData('cc_exp_month') ?>
		                <?php foreach ($this->getCcMonths() as $k=>$v): ?>
		                    <option value="<?php echo $k?$k:'' ?>"<?php if($k==$_ccExpMonth): ?> selected="selected"<?php endif ?>><?php echo $v ?></option>
		                <?php endforeach ?>
		                </select>
		            </div>
		            <div class="v-fix">
		                <?php $_ccExpYear = $this->getInfoData('cc_exp_year') ?>
		                <select id="<?php echo $_code ?>_expiration_yr" name="payment[cc_exp_year]" class="year required-entry">
		                <?php foreach ($this->getCcYears() as $k=>$v): ?>
		                    <option value="<?php echo $k?$k:'' ?>"<?php if($k==$_ccExpYear): ?> selected="selected"<?php endif ?>><?php echo $v ?></option>
		                <?php endforeach ?>
		                </select>
		            </div>
		        </div>
		    </li>
		    <?php echo $this->getChildHtml() ?>
		    <?php if($this->hasVerification()): ?>
		    <li id="<?php echo $_code ?>_cc_type_cvv_div">
		        <label for="<?php echo $_code ?>_cc_cid" class="required"><em>*</em><?php echo $this->__('Card Verification Number') ?></label>
		        <div class="input-box">
		            <div class="v-fix">
		                <input type="text" title="<?php echo $this->__('Card Verification Number') ?>" class="input-text cvv required-entry validate-cc-cvn" id="<?php echo $_code ?>_cc_cid" name="payment[cc_cid]" value="" />
		            </div>
		            <a href="#" class="cvv-what-is-this"><?php echo $this->__('What is this?') ?></a>
		        </div>
		    </li>
		    <?php endif; ?>
	<?php endif; ?>
</ul>
