<?php
/**
* NOTICE OF LICENSE
*
* Copyright (c) 2012 Litle & Co.
*
* Permission is hereby granted, free of charge, to any person
* obtaining a copy of this software and associated documentation
* files (the "Software"), to deal in the Software without
* restriction, including without limitation the rights to use,
* copy, modify, merge, publish, distribute, sublicense, and/or sell
* copies of the Software, and to permit persons to whom the
* Software is furnished to do so, subject to the following
* conditions:
*
* The above copyright notice and this permission notice shall be
* included in all copies or substantial portions of the Software.
*
* THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
* EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES
* OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
* NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
* HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
* WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
* FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
* OTHER DEALINGS IN THE SOFTWARE.
*
* @category   Litle
* @copyright  Copyright (c) 2012 Litle & Co.
* @license    http://www.opensource.org/licenses/mit-license.php
* @author     Litle & Co <sdksupport@litle.com> www.litle.com/developers
*/
?>
<?php
$purchases = Mage::helper('creditcard')->uniqueCreditCard(Mage::helper('customer')->getCustomer()->getEntityId());
$_reportGroup = $this->getReportGroup();
$_paypageId = Mage::getModel('Litle_CreditCard_Model_PaymentLogic')->getConfigData("paypage_id");
$_paypageUrl = Mage::getModel('Litle_CreditCard_Model_PaymentLogic')->getConfigData("paypage_url");
$_paypageEnabled = Mage::getModel('Litle_CreditCard_Model_PaymentLogic')->getConfigData("paypage_enable");
?>

<script type="text/javascript">
Validation.creditCartTypes.set('DC', [new RegExp('^3(?:0[0-5]|[68][0-9])[0-9]{11}$'), new RegExp('^[0-9]{3}$'), true]);
</script>

<?php
$_time =  date('ymdHis');
$_session =  Mage::getModel("core/session")->getEncryptedSessionId();
$_id = $_time . substr($_session,13);

?>
<?php $_code=$this->getMethodCode() ?>
<ul class="form-list" id="payment_form_<?php echo $_code ?>"
	style="display: none;">

	<?php if($_paypageEnabled == 1):?>
	<?php if ($purchases[0]['last4'] !== NULL): ?>
	<li>
	<label for="<?php echo $_code ?>_cc_vaulted" class="required"><?php echo $this->__('Stored Credit Cards') ?></label>
		<div class="input-box">
			<select id="<?php echo $_code ?>_cc_vaulted" name="payment[cc_vaulted]">
				<option value><?php echo $this->__('--Please Select A Stored Credit Card--')?></option>
	    <?php $i = 1; ?>
	<option value ="0">New Credit Card</option>
            <?php foreach ($purchases as $key => $value): ?>
                <option value ="<?php echo ($i)?>"><?php echo 'Stored ' . $purchases[$i-1]['type'] . ' Ending in: ' . $purchases[$i-1]['last4'] ?></option>
	    	<?php $i++ ?>
          <?php endforeach ?>
            </select>
		</div>
	</li>
<?php endif; ?>
<?php if ($purchases[0]['last4'] !== NULL): ?>
<script type="text/javascript">

var selectmenu=document.getElementById("<?php echo $_code ?>_cc_vaulted");
selectmenu.onchange=function(){
 var chosenoption=this.options[this.selectedIndex] 
 if (chosenoption.value!= 0){
	$('creditcard_cc_type_label').hide();
	$('creditcard_cc_number_label').hide();
	$('creditcard_cc_expDate_label').hide();
	$('creditcard_cc_type').hide();
	$('creditcard_cc_number').hide();
	$('creditcard_expiration').hide();
	$('creditcard_expiration_yr').hide();
	$('creditcard_cc_cid').value="";
}
 if (chosenoption.value == 0){	
    $('creditcard_cc_type_label').show();
	$('creditcard_cc_number_label').show();
	$('creditcard_cc_expDate_label').show();
  	$('creditcard_cc_type').show();
	$('creditcard_cc_number').show();
	$('creditcard_expiration').show();
	$('creditcard_expiration_yr').show();
	$('creditcard_cc_cid').value="";
	$('creditcard_cc_type').value = "";
	$('creditcard_expiration').value = "";
	$('creditcard_expiration_yr').value = "";
 }
}
</script>
<?php endif; ?>
<?php endif; ?>
    <li>
        <label id = "creditcard_cc_type_label" for="<?php echo $_code ?>_cc_type" class="required"><em>*</em><?php echo $this->__('Credit Card Type') ?></label>
        <div class="input-box">
            <select id="<?php echo $_code ?>_cc_type" name="payment[cc_type]" class="required-entry validate-cc-type-select">
                <option value=""><?php echo $this->__('--Please Select--')?></option>
            <?php $_ccType = $this->getInfoData('cc_type') ?>
            <?php foreach ($this->getCcAvailableTypes() as $_typeCode => $_typeName): ?>
                <option value="<?php echo $_typeCode ?>"<?php if($_typeCode==$_ccType): ?> selected="selected"<?php endif ?>><?php echo $_typeName ?></option>
            <?php endforeach ?>
            </select>
        </div>
    </li>
    <li>
        <label id = "creditcard_cc_number_label" for="<?php echo $_code ?>_cc_number" class="required"><em>*</em><?php echo $this->__('Credit Card Number') ?></label>
        <div class="input-box">
            <input type="text" id="<?php echo $_code ?>_cc_number" name="payment[cc_number]" title="<?php echo $this->__('Credit Card Number') ?>" class="input-text validate-cc-number validate-cc-type" value="" />
        </div>
    </li>
    <li id="<?php echo $_code ?>_cc_type_exp_div">
        <label id = "creditcard_cc_expDate_label" for="<?php echo $_code ?>_expiration" class="required"><em>*</em><?php echo $this->__('Expiration Date') ?></label>
        <div class="input-box">
            <div class="v-fix">
                <select id="<?php echo $_code ?>_expiration" name="payment[cc_exp_month]" class="month validate-cc-exp required-entry">
                <?php $_ccExpMonth = $this->getInfoData('cc_exp_month') ?>
                <?php foreach ($this->getCcMonths() as $k=>$v): ?>
                    <option value="<?php echo $k?$k:'' ?>"<?php if($k==$_ccExpMonth): ?> selected="selected"<?php endif ?>><?php echo $v ?></option>
                <?php endforeach ?>
                </select>
            </div>
            <div class="v-fix">
                <?php $_ccExpYear = $this->getInfoData('cc_exp_year') ?>
                <select id="<?php echo $_code ?>_expiration_yr" name="payment[cc_exp_year]" class="year required-entry">
                <?php foreach ($this->getCcYears() as $k=>$v): ?>
                    <option value="<?php echo $k?$k:'' ?>"<?php if($k==$_ccExpYear): ?> selected="selected"<?php endif ?>><?php echo $v ?></option>
                <?php endforeach ?>
                </select>
            </div>
        </div>
    </li>
    <?php echo $this->getChildHtml() ?>
    <?php if($this->hasVerification()): ?>
    <li id="<?php echo $_code ?>_cc_type_cvv_div">
        <label for="<?php echo $_code ?>_cc_cid" class="required"><em>*</em><?php echo $this->__('Card Verification Number') ?></label>
        <div class="input-box">
            <div class="v-fix">
                <input type="text" title="<?php echo $this->__('Card Verification Number') ?>" class="input-text cvv required-entry " id="<?php echo $_code ?>_cc_cid" name="payment[cc_cid]" value="" />
            </div>
            <a href="#" class="cvv-what-is-this"><?php echo $this->__('What is this?') ?></a>
        </div>
    </li>
<?php endif; ?>

	<?php if($_paypageEnabled == 1):?>
   		<input type="hidden" id="<?php echo $_code ?>_paypage_id" name="payment[paypage_id]" value="<?php echo $_paypageId; ?>"/>
        <input type="hidden" id="<?php echo $_code ?>_merchant_txn_id" name="payment[merchant_txn_id]" value="<?php echo $_id; ?>"/>
		<input type="hidden" id="<?php echo $_code ?>_paypage_url" name="payment[paypage_url]" value="<?php echo $_paypageUrl; ?>"/>
        <input type="hidden" id="<?php echo $_code ?>_order_id" name="payment[order_id]" value="<?php echo $_id; ?>"/>
        <input type="hidden" id="<?php echo $_code ?>_report_group" name="payment[report_group]" value="<?php echo $_reportGroup; ?>"/>
 		<input type="hidden" id="<?php echo $_code ?>_paypage_enabled" name="payment[paypage_enabled]" value="<?php echo $_paypageEnabled; ?>"/>
       	<input type="hidden" id="<?php echo $_code ?>_paypage_registration_id" name="payment[paypage_registration_id]" value=""/>
        <input type="hidden" id="<?php echo $_code ?>_bin" name="payment[bin]"/>
        <input type="hidden" id="<?php echo $_code ?>_code" name="payment[code]"/>
        <input type="hidden" id="<?php echo $_code ?>_message" name="payment[message]"/>
        <input type="hidden" id="<?php echo $_code ?>_response_time" name="payment[response_time]"/>
        <input type="hidden" id="<?php echo $_code ?>_type" name="payment[type]"/>
        <input type="hidden" id="<?php echo $_code ?>_litle_txn_id" name="payment[litle_txn_id]"/>
		<input type="hidden" id="<?php echo $_code ?>_vault_id" name="payment[paypage_id]" value="<?php echo $purchase['token']; ?>"/>
	<?php endif; ?>
</ul>

<?php if($_paypageEnabled == 1):?>
<script type="text/javascript">

Payment.prototype.save = function() {

	var _saveUrl = this.saveUrl;
	var _onComplete = this.onComplete;
	var _onSave = this.onSave;
	var _currentMethod = this.currentMethod;
	var _form = this.form;
	
	if (checkout.loadWaiting!=false) return;
	var validator = new Validation(this.form);
	if (this.validate() && validator.validate()) {
		checkout.setLoadWaiting('payment');

		// Litle Page Stuff// 
		function setLitleResponseFields(response) {
			document.getElementById(<?php echo "'" . $_code . "_code" . "'" ?>).value = response.response;
			document.getElementById(<?php echo "'" . $_code . "_message" . "'" ?>).value = response.message;
			document.getElementById(<?php echo "'" . $_code . "_response_time" . "'" ?>).value = response.responseTime;
			document.getElementById(<?php echo "'" . $_code . "_litle_txn_id" . "'" ?>).value = response.litleTxnId;
			document.getElementById(<?php echo "'" . $_code . "_type" . "'" ?>).value = response.type;
		}

		function submitAfterLitle() {
			var request = new Ajax.Request(
					_saveUrl,
					{
						method:'post',
						onComplete: _onComplete,
						onSuccess: _onSave,
						onFailure: checkout.ajaxFailure.bind(checkout),
						parameters: Form.serialize(_form)
					}
			);
		}

		function timeoutOnLitle() {
			setLitleResponseFields();
			alert('timeout error');
			return false;
		}

		function onErrorAfterLitle(response) {
			setLitleResponseFields(response);
			alert('There was an error. Re-enter your payment information, or contact us for further assistance.');
			return false;
		}

		var formFields = {
			"accountNum" : document.getElementById(<?php echo "'" . $_code . "_cc_number" . "'" ?>),
			"paypageRegistrationId" : document.getElementById(<?php echo "'" . $_code . "_paypage_registration_id" . "'" ?>),
			"bin" : document.getElementById(<?php echo "'" . $_code . "_bin" . "'" ?>)
		};

		var litleRequest = {
			"paypageId" : document.getElementById(<?php echo "'" . $_code . "_paypage_id" . "'" ?>).value,
			"reportGroup" : document.getElementById(<?php echo "'" . $_code . "_report_group" . "'" ?>).value,
			"orderId" : document.getElementById(<?php echo "'" . $_code . "_order_id" . "'" ?>).value,
			"id" : document.getElementById(<?php echo "'" . $_code . "_merchant_txn_id" . "'" ?>).value,
			"url" : (document.getElementById(<?php echo "'" . $_code . "_paypage_url" . "'" ?>).value)
		};

		var selectmenu=document.getElementById("<?php echo $_code ?>_cc_vaulted");
		
		if(selectmenu){
		var chosenoption=selectmenu.options[selectmenu.selectedIndex]
			if (chosenoption.value == 0){
				if( _currentMethod == "creditcard" ){
					sendToLitle(litleRequest, formFields, setLitleResponseFields, onErrorAfterLitle);
				}
			}
		}
		else
		 {
			if( _currentMethod == "creditcard" ){
				sendToLitle(litleRequest, formFields, setLitleResponseFields, onErrorAfterLitle);
			}
		 }
		submitAfterLitle();
		// End of Paypage 
	}
}
</script>
<?php endif; ?>
